apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: firefly-auth
  namespace: littlesparrows
spec:
  forwardAuth:
    address: http://backend.littlesparrows.svc.cluster.local:5000/api/developer/authorize
    trustForwardHeader: true
    authRequestHeaders:
      - Cookie
